/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DotsearchAutocomplete {
        "endpoint": string | undefined;
        "fuzzines": 0 | 1 | 2;
        "loading": boolean;
        "placeholder": string;
        "token": string;
        "value": string;
    }
}
declare global {
    interface HTMLDotsearchAutocompleteElement extends Components.DotsearchAutocomplete, HTMLStencilElement {
    }
    var HTMLDotsearchAutocompleteElement: {
        prototype: HTMLDotsearchAutocompleteElement;
        new (): HTMLDotsearchAutocompleteElement;
    };
    interface HTMLElementTagNameMap {
        "dotsearch-autocomplete": HTMLDotsearchAutocompleteElement;
    }
}
declare namespace LocalJSX {
    interface DotsearchAutocomplete {
        "endpoint"?: string | undefined;
        "fuzzines"?: 0 | 1 | 2;
        "loading"?: boolean;
        "placeholder"?: string;
        "token"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "dotsearch-autocomplete": DotsearchAutocomplete;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dotsearch-autocomplete": LocalJSX.DotsearchAutocomplete & JSXBase.HTMLAttributes<HTMLDotsearchAutocompleteElement>;
        }
    }
}
